spring.application.name=job-portal

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://dpg-d6s2i64hg0os73eunq10-a.oregon-postgres.render.com/job_portal_lq8b}
spring.datasource.username=${DATABASE_USERNAME:job_portal_lq8b_user}
spring.datasource.password=${DATABASE_PASSWORD:eAfWFzxPRh2SgkEpU1cvA5zxhyuOocxm}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
frontend.url=${FRONTEND_URL:https://hire-flow-interview-scheduling-plat.vercel.app/}